//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lastpraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int Код_изделия { get; set; }
        public string Название_предприятия { get; set; }
        public string Адрес_предприятия { get; set; }
        public string Телефон_предприятия { get; set; }
    
        public virtual good good { get; set; }
    }
}
