//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lastpraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class good
    {
        public int Код_изделия { get; set; }
        public string Название_изделия { get; set; }
        public string Типовое { get; set; }
        public string Цель { get; set; }
        public long Объём_выпуска { get; set; }
    
        public virtual company company { get; set; }
        public virtual material material { get; set; }
    }
}
