//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lastpraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public int Код_изделия { get; set; }
        public string Название_материала { get; set; }
        public string Тип { get; set; }
        public string Единица_измерения { get; set; }
        public int Цена { get; set; }
    
        public virtual good good { get; set; }
        public virtual property property { get; set; }
        public virtual year year { get; set; }
    }
}
