//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lastpraktika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class manufactureEntities : DbContext
    {
        private static manufactureEntities context;

        public static manufactureEntities GetContext()
        {
            if (context == null) context = new manufactureEntities();
            return context;
        }
        public manufactureEntities()
            : base("name=manufactureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<good> goods { get; set; }
        public virtual DbSet<material> materials { get; set; }
        public virtual DbSet<property> properties { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<year> years { get; set; }
    }
}
