//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lastpraktika
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property()
        {
            this.materials = new HashSet<material>();
        }
    
        public string Название_материала { get; set; }
        public int Кол_мат { get; set; }
        public System.DateTime Дата_установ { get; set; }
        public System.DateTime Дата_отмены { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<material> materials { get; set; }
    }
}
